{% set version = "3.2.0.rc1" %}

{% set commit = "db10582cb0f8fecba654153d248142489ab6b883" %}
{% set sha256 = "a8225900d33e50f3495038b131c6afef36468dcdb38a6bc922344b67c21402ac" %}

package:
  name: gudhi
  version: {{ version }}

source:
  url: https://github.com/GUDHI/gudhi-devel/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # for windows, no python 2.X
  skip: true  # [win and py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - setuptools
    - cython
    - pybind11
    - boost-cpp
    - eigen
    - cgal-cpp 5.0.1
  run:
    - python
    - numpy
    - setuptools
    - boost-cpp
    - cgal-cpp 5.0.1

test:
  commands:
    - test -f ${PREFIX}/include/gudhi/Simplex_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\gudhi\Simplex_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
    - python -c "import gudhi; diag1 = [[2.7, 3.7], [9.6, 14.0], [34.2, 34.974], [3.0, float('Inf')]]; diag2 = [[2.8, 4.45], [9.5, 14.1], [3.2, float('Inf')]]; assert gudhi.bottleneck_distance(diag1, diag2) == 0.75"
about:
  home: http://gudhi.gforge.inria.fr/
  license: MIT/GPL3
  license_file: LICENSEpybind/python_example/blob/master/conda.recipe/meta.yaml
  summary: Geometry Understanding in Higher Dimensions
  description: |
    The GUDHI library is a generic open source C++ library, with a Python
    interface, for Topological Data Analysis (TDA) and Higher Dimensional
    Geometry Understanding. The library offers state-of-the-art data structures
    and algorithms to construct simplicial complexes and compute persistent
    homology.
  doc_url: http://gudhi.gforge.inria.fr/python/{{ version }}/
extra:
  recipe-maintainers:
    - VincentRouvreau
