{% set version = "3.2.0.rc1" %}

{% set commit = "8dfc31c57586b07524728c939593f216c5d640f5" %}
{% set sha256 = "c7fd1f1bd218dd24df44ddd047c325eca4786d4110663d4b2e997c5c0fe99b6d" %}

package:
  name: gudhi
  version: {{ version }}

source:
  git_url: https://github.com/GUDHI/gudhi-devel.git
  git_rev: tags/gudhi-release-{{ version }}
  git_depth: 1

build:
  number: 0
  # for windows, no python 2.X
  skip: true  # [win and py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - git
    - python
    - numpy
    - setuptools
    - cython
    - pybind11
    - boost-cpp
    - eigen
    - cgal-cpp 5.0.1
  run:
    - python
    - numpy
    - setuptools
    - boost-cpp
    - cgal-cpp 5.0.1

test:
  requires:
    - pytest
    - python
    - matplotlib
    - scipy
    - scikit-learn
    - POT
    - tensorflow
    - torch
    - pykeops
    - hnswlib
    - eagerpy
  source_files:
    - src/python/test
  commands:
    - test -f ${PREFIX}/include/gudhi/Simplex_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\gudhi\Simplex_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
    - py.test
about:
  home: http://gudhi.gforge.inria.fr/
  license: MIT/GPL3
  license_file: LICENSE
  summary: Geometry Understanding in Higher Dimensions
  description: |
    The GUDHI library is a generic open source C++ library, with a Python
    interface, for Topological Data Analysis (TDA) and Higher Dimensional
    Geometry Understanding. The library offers state-of-the-art data structures
    and algorithms to construct simplicial complexes and compute persistent
    homology.
  doc_url: http://gudhi.gforge.inria.fr/python/{{ version }}/
extra:
  recipe-maintainers:
    - VincentRouvreau
